#### general setup ####
### paths
# outdir :
version : "v2"
workdir : "/ebio/abt6_projects7/dliso/dlis/leon_pipeline/analysis/benchmarking"

pools : ['pool1']

### mappings
# demultiplexing
sample2pools : {'at6923':['pool1'],
                'at6929':['pool1'],
                'at7143':['pool1'],
                'at8285':['pool1'],
                'at9104':['pool1'],
                'at9336':['pool1'],
                'at9503':['pool1'],
                'at9578':['pool1']}

# stats:
pool2samples : {'pool1':['at6923', 'at6929', 'at7143', 'at8285', 'at9104', 'at9336', 'at9503', 'at9578']}


barcodes: ['bc1001_5p--bc1001_3p', 'bc1002_5p--bc1002_3p', 'bc1003_5p--bc1003_3p',
            'bc1008_5p--bc1008_3p',
            'bc1009_5p--bc1009_3p',
            'bc1010_5p--bc1010_3p',
            'bc1011_5p--bc1011_3p',
            'bc1012_5p--bc1012_3p']

# renaming
bc2sample : [{'bc1001_5p--bc1001_3p':'at6923',
            'bc1002_5p--bc1002_3p':'at6929',
            'bc1003_5p--bc1003_3p':'at7143',
            'bc1008_5p--bc1008_3p':'at8285',
            'bc1009_5p--bc1009_3p':'at9104',
            'bc1010_5p--bc1010_3p':'at9336',
            'bc1011_5p--bc1011_3p':'at9503',
            'bc1012_5p--bc1012_3p':'at9578'}]


# renaming
name2bc : [{'at6923':'bc1001_5p--bc1001_3p',
            'at6929':'bc1002_5p--bc1002_3p',
            'at7143':'bc1003_5p--bc1003_3p',
            'at8285':'bc1008_5p--bc1008_3p',
            'at9104':'bc1009_5p--bc1009_3p',
            'at9336':'bc1010_5p--bc1010_3p',
            'at9503':'bc1011_5p--bc1011_3p',
            'at9578':'bc1012_5p--bc1012_3p'}]

# (sub)set of samples to map and collapse
samples2map: ['at6923','at6929','at7143','at8285','at9104','at9336','at9503','at9578']

#### parameters ####
# isoseq processing
#ccs :
#lima : 
#refine :

# mapping
#pbmm2 :
#minimap2 : 

# collapsing
pb_c : "--min-aln-identity 0.99 --max-fuzzy-junction 0 --max-5p-diff 10 --max-3p-diff 5"
stringtie_c : "-s 0.99 -g -1 -t -R -E 10 --rf"
tama_c : "-x capped -a 10 -m 0 -z 5 -i 99 -sj sj_priority -sjt 10 -lde 2"

# samples to compare against ref
samples2comp: ['at6923','at6929','at7143','at8285','at9104','at9336','at9503','at9578']

######################## PASA ########################
pasa_settings: ['set1']
# pasa (only temporary, since we do not have a solution for the araport gff)
samples2update: ['at6923','at6929','at7143','at8285','at9104','at9336','at9503','at9578']
